### ISSUE TITLE
ImageNet scripts

### ISSUE THREAD

**Issue by rahimentezari** [UCMerced-ML/LC-model-compression#1]
Thanks for such great work. I have been following your works and I enjoyed them. 
I was wondering if you can upload the scripts and pre-trained models for the ImageNet experiments. Have you also tried ResNet50 with ImageNet?

Thanks

**Comment by akamaster** [comment]
Hi @rahimentezari, thanks a lot for the interest in our work. We will upload AlexNet models from our [Rank Selection paper](https://openaccess.thecvf.com/content_CVPR_2020/html/Idelbayev_Low-Rank_Compression_of_Neural_Nets_Learning_the_Rank_of_Each_CVPR_2020_paper.html) shortly (a day at most), and the corresponding training script by the end of this week (probably on the weekend). Unfortunately, we haven't tried ResNet models on the ImageNet yet.

**Comment by akamaster** [comment]
@rahimentezari, we have just added [the low-rank AlexNet models](https://github.com/UCMerced-ML/LC-model-compression/tree/master/examples/low_rank_alexnets). We will upload the training scripts soon
